const ContainerList = [
  {
    id: 1,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty417/product/media/images/20220506/0/102443165/80327914/1/1_org_zoom.jpg",
    tag: "Nike",
    name: "Kadın Siyah Yanı Şeritli Cepli Eşofman Altı 89162",
    star: 4,
    view: 11342,
    price: 110,
    alt: "new",
    video: false,
    coupon: true,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "Nike",
    bodySize: "XXS",
    trotterType: "Dar Paça",
    pattern: "Basic",
    materiel: "Dalgıç Kumaş",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#F5E0CC",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 2,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty572/product/media/images/20221020/9/197769813/160445909/1/1_org_zoom.jpg",
    tag: "Mavi",
    name: "Kadın Siyah Renk Eşofman Altı",
    star: 3,
    view: 4926,
    price: 61,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "Mavi",
    bodySize: "XS",
    trotterType: "Fermuarlı Paça",
    pattern: "Wide Leg",
    materiel: "Likra",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Başarılı Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#FFFFFF",
    ninePoint: true,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 3,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty508/product/media/images/20220815/16/160229322/224779670/2/2_org_zoom.jpg",
    tag: "TRENDYOLMILLA",
    name: "Antrasit Yıkamalı Wide Leg Eşofman Altı",
    star: 4,
    view: 1894,
    price: 275.99,
    alt: "new",
    video: true,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "TRENDYOLMILLA",
    bodySize: "M",
    trotterType: "Lastikli Paça",
    pattern: "Jogger",
    materiel: "Polycotton",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#A52C36",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 4,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty565/product/media/images/20221016/2/194629668/80256395/2/2_org_zoom.jpg",
    tag: "Koton",
    name: "Kadın Siyah Paçası Lastikli Eşofman",
    star: 4,
    view: 20697,
    price: 249.50,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "Koton",
    bodySize: "S",
    trotterType: "Normal Paça",
    pattern: "Fitted",
    materiel: "Polyester",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "İki Yıldızlı Ürün",
    color: "#EDE9DE",
    ninePoint: true,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 5,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/17/47599109/82766003/3/3_org_zoom.jpg",
    tag: "TRENDYOLMİLLA",
    name: "Gri Selanik Basic Örme Eşofman Altı",
    star: 1,
    view: 13180,
    price: 156.99,
    alt: "new",
    video: false,
    coupon: true,
    discount: false,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "adidas",
    bodySize: "L",
    trotterType: "Jogger",
    pattern: "Comfort",
    materiel: "Polyester",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "1 yıldız ve üzeri",
    starProduct: "",
    color: "#DDDDDD",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 6,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty143/product/media/images/20210708/11/108255393/61599742/1/1_org_zoom.jpg",
    tag: "TRENDYOLMILLA",
    name: "Unisex Sauna - Zayıflatıcı Eşofman",
    star: 2,
    view: 602,
    price: 349.99,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "TRENDYOLMILLA",
    bodySize: "XL",
    trotterType: "Boru Paça",
    pattern: "Straight",
    materiel: "Kadife",
    waistType: "Yüksek Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Başarılı Satıcı",
    productRating: "2 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#8B9955",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 7,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty613/product/media/images/20221129/17/223897525/195866519/1/1_org_zoom.jpg",
    tag: "Defacto",
    name: "Siyah Dar Kalıp Jogger Eşofman Altı",
    star: 3,
    view: 7044,
    price: 59.99,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "Defacto",
    bodySize: "XXL",
    trotterType: "Lastiksiz Paça",
    pattern: "Standart",
    materiel: "Kadife",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Onaylanmış Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#8B572A",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 8,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty356/product/media/images/20220309/16/66427906/120124808/1/1_org_zoom.jpg",
    tag: "TRENDYOLMILLA",
    name: "Erkek gri günlük eşofman altı jeans fashion",
    star: 5,
    view: 874,
    price: 179.99,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "TRENDYOLMILLA",
    bodySize: "2XL",
    trotterType: "Geniş Paça",
    pattern: "Slim Fit",
    materiel: "Pamuklu",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#1F3897",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 9,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty581/product/media/images/20221026/9/202614602/75953918/1/1_org_zoom.jpg",
    tag: "Addax",
    name: "Kadın Siyah Paçası Lastikli Eşofman",
    star: 4,
    view: 4417,
    price: 279.50,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "Addax",
    bodySize: "3XL",
    trotterType: "Dar Paça",
    pattern: "Normal",
    materiel: "%100 Organik Pamuk",
    waistType: "Normal Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "İki Yıldızlı Ürün",
    color: "#71B2FF",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 10,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty201/product/media/images/20211018/15/151687295/59472828/1/1_org_zoom.jpg",
    tag: "Stradivarius",
    name: "Yakalı Kol Garnili Lacivert Erkek Eşofman Takım",
    star: 5,
    view: 772,
    price: 494.92,
    alt: "new",
    video: true,
    coupon: false,
    discount: true,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "Stradivarius",
    bodySize: "4XL",
    trotterType: "Fermuarlı Paça",
    pattern: "Büyük Beden",
    materiel: "Kadife",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#DE001B",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 11,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty514/product/media/images/20220824/12/164928245/551339508/1/1_org_zoom.jpg",
    tag: "Pull & Bear",
    name: "Unisex Gri Wrst 2 Iplik Eşofman Altı",
    star: 3,
    view: 6,
    price: 139,
    alt: "new",
    video: false,
    coupon: true,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "Pull & Bear",
    bodySize: "XXS",
    trotterType: "Dar Paça",
    pattern: "Basic",
    materiel: "Dalgıç Kumaş",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#7ED321",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 12,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty584/product/media/images/20221101/11/204883251/610461304/1/1_org_zoom.jpg",
    tag: "HUMMEL",
    name: "Bohem Giyim Gri Butterfly Baskılı Eşofman Altı",
    star: 5,
    view: 1329,
    price: 130,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "HUMMEL",
    bodySize: "XS",
    trotterType: "Fermuarlı Paça",
    pattern: "Wide Leg",
    materiel: "Likra",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#FFFFFF",
    ninePoint: true,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 13,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty453/product/media/images/20220616/23/126518814/147550442/1/1_org_zoom.jpg",
    tag: "LC Waikiki",
    name: "Yüksek Belli Jogger Yazlık Eşofman Altı",
    star: 4,
    view: 3237,
    price: 60.50,
    alt: "new",
    video: true,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "LC Waikiki",
    bodySize: "M",
    trotterType: "Lastikli Paça",
    pattern: "Jogger",
    materiel: "Polycotton",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#A52C36",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 14,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty607/product/media/images/20221122/9/219462476/61621499/1/1_org_zoom.jpg",
    tag: "Addax",
    name: "Kadın Ekru Paçası Lastikli Eşofman",
    star: 4,
    view: 6595,
    price: 119.50,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "Addax",
    bodySize: "S",
    trotterType: "Normal Paça",
    pattern: "Fitted",
    materiel: "Polyester",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "İki Yıldızlı Ürün",
    color: "#EDE9DE",
    ninePoint: true,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 15,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty180/product/media/images/20210923/13/135748859/248397065/1/1_org_zoom.jpg",
    tag: "adidas",
    name: "Kadın 2 Li Eşofman Takımı",
    star: 4,
    view: 4590,
    price: 849.99,
    alt: "new",
    video: false,
    coupon: true,
    discount: false,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "adidas",
    bodySize: "L",
    trotterType: "Jogger",
    pattern: "Comfort",
    materiel: "100% Pamuk",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "",
    color: "#8331CC",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 16,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty613/product/media/images/20221129/17/223897569/159292485/1/1_org_zoom.jpg",
    tag: "TRENDYOL MAN",
    name: "Siyah Dar Kalıp Jogger Eşofman Altı",
    star: 3,
    view: 7137,
    price: 99,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "TRENDYOL MAN",
    bodySize: "XL",
    trotterType: "Boru Paça",
    pattern: "Straight",
    materiel: "Kadife",
    waistType: "Yüksek Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Başarılı Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#8B9955",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 17,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty606/product/media/images/20221121/11/219053325/121027894/1/1_org_zoom.jpg",
    tag: "TRENDYOL MAN",
    name: "MARSHALL Erkek Nakış Detaylı Eşofman",
    star: 4,
    view: 3301,
    price: 424.96,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "TRENDYOL MAN",
    bodySize: "XXL",
    trotterType: "Lastiksiz Paça",
    pattern: "Standart",
    materiel: "100% Pamuk",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#FFA8E7",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 18,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty597/product/media/images/20221112/10/212949692/127036653/1/1_org_zoom.jpg",
    tag: "TRENDYOLMILLA",
    name: "Erkek gri günlük eşofman altı jeans fashion",
    star: 5,
    view: 1618,
    price: 269.99,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "TRENDYOLMILLA",
    bodySize: "2XL",
    trotterType: "Geniş Paça",
    pattern: "Slim",
    materiel: "Pamuk Polyester",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#1F3897",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 19,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty541/product/media/images/20220927/14/180313831/580716594/1/1_org_zoom.jpg",
    tag: "Defacto",
    name: "Polar Kumaş Oversize Antrasit Erkek Eşofman Altı",
    star: 4,
    view: 202,
    price: 249.50,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "Defacto",
    bodySize: "3XL",
    trotterType: "Dar Paça",
    pattern: "Regular Jogger",
    materiel: "Pamuk Polyester",
    waistType: "Normal Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "İki Yıldızlı Ürün",
    color: "#FFA8E7",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 20,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty502/product/media/images/20220810/16/157547250/477611586/3/3_org_zoom.jpg",
    tag: "TRENDYOL MAN",
    name: "Siyah Erkek Lastik Paça Eşofman Altı",
    star: 5,
    view: 37,
    price: 124.99,
    alt: "new",
    video: true,
    coupon: false,
    discount: true,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "TRENDYOL MAN",
    bodySize: "4XL",
    trotterType: "Fermuarlı Paça",
    pattern: "Relaxed",
    materiel: "Kadife",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#FFE500",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 21,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty547/product/media/images/20221001/22/183493527/585860103/1/1_org_zoom.jpg",
    tag: "adidas",
    name: "Unisex Nasa Baskılı Eşofman Takımı",
    star: 3,
    view: 170,
    price: 194.90,
    alt: "new",
    video: false,
    coupon: true,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "adidas",
    bodySize: "XXS",
    trotterType: "Dar Paça",
    pattern: "Oversize",
    materiel: "%100 Organik Pamuk",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#F5E0CC",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 22,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty181/product/media/images/20210923/9/135611587/248830015/1/1_org_zoom.jpg",
    tag: "Pull & Bear",
    name: "Siyah Erkek Eşofman Takımı",
    star: 5,
    view: 484,
    price: 599.99,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "Pull & Bear",
    bodySize: "XS",
    trotterType: "Fermuarlı Paça",
    pattern: "Oversize",
    materiel: "Pamuk-Polyester",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#FFFFFF",
    ninePoint: true,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 23,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty522/product/media/images/20220904/12/169004167/558809129/1/1_org_zoom.jpg",
    tag: "Defacto",
    name: "Relax Fit Sürdürülebilir Eşofman Altı  ",
    star: 4,
    view: 5692,
    price: 199.99,
    alt: "new",
    video: true,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "Defacto",
    bodySize: "M",
    trotterType: "Lastikli Paça",
    pattern: "Jogger",
    materiel: "Pamuk Karışımlı",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#FFE500",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 24,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty182/product/media/images/20210923/9/135610017/248828290/1/1_org_zoom.jpg",
    tag: "Pull & Bear",
    name: "Bej Erkek Eşofman Takımı",
    star: 5,
    view: 3763,
    price: 599.99,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "Pull & Bear",
    bodySize: "S",
    trotterType: "Normal Paça",
    pattern: "Oversize",
    materiel: "Polyester",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "İki Yıldızlı Ürün",
    color: "#565656",
    ninePoint: true,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 25,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty516/product/media/images/20220824/18/165147926/457731547/2/2_org_zoom.jpg",
    tag: "TRENDYOLMILLA",
    name: " Lacivert Loose Baskılı Eşofman Altı",
    star: 4,
    view: 2041,
    price: 189.99,
    alt: "new",
    video: false,
    coupon: true,
    discount: false,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "TRENDYOLMILLA",
    bodySize: "L",
    trotterType: "Jogger",
    pattern: "Comfort",
    materiel: "Pamuk Karışımlı",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "",
    color: "#46C49E",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 26,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty493/product/media/images/20220729/17/152017170/432965549/2/2_org_zoom.jpg",
    tag: "TRENDYOLMILLA",
    name: "Gri Kapitone Loose Jogger Örme Eşofman Altı",
    star: 3,
    view: 372,
    price: 62.99,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "TRENDYOLMILLA",
    bodySize: "XL",
    trotterType: "Boru Paça",
    pattern: "Oversize",
    materiel: "Pamuk-Polyester-Elastan",
    waistType: "Yüksek Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Başarılı Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#8B9955",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
  {
    id: 27,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty495/product/media/images/20220801/13/153049070/533113390/2/2_org_zoom.jpg",
    tag: "Koton",
    name: "MARSHALL Erkek Düz Gri Eşofman",
    star: 4,
    view: 500,
    price: 173.90,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "Koton",
    bodySize: "XXL",
    trotterType: "Lastiksiz Paça",
    pattern: "Relaxed",
    materiel: "Kadife",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#F5A623",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
    buyWin: false,
  },
  {
    id: 28,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty537/product/media/images/20220922/11/178384097/575196595/1/1_org_zoom.jpg",
    tag: "LC Waikiki",
    name: "Kapüşonlu Paraşüt Kumaş Kadın Eşofman",
    star: 5,
    view: 320,
    price: 1233.99,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "LC Waikiki",
    bodySize: "2XL",
    trotterType: "Geniş Paça",
    pattern: "Slim Fit",
    materiel: "Pamuklu",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#1F3897",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 29,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty252/product/media/images/20211122/16/550943/75312424/1/1_org_zoom.jpg",
    tag: "Stradivarius",
    name: "Mad Girls Gri Kadın Eşofman",
    star: 2,
    view: 55,
    price: 259.90,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "Stradivarius",
    bodySize: "3XL",
    trotterType: "Dar Paça",
    pattern: "Relaxed",
    materiel: "Penye",
    waistType: "Normal Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "2 yıldız ve üzeri",
    starProduct: "İki Yıldızlı Ürün",
    color: "#7ED321",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: false,
  },
  {
    id: 30,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty570/product/media/images/20221019/19/197493669/597872845/1/1_org_zoom.jpg",
    tag: "Puma",
    name: "Sportswear Essential - Kadın Eşofman Altı",
    star: 3,
    view: 751,
    price: 1289,
    alt: "new",
    video: true,
    coupon: false,
    discount: true,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "Puma",
    bodySize: "4XL",
    trotterType: "Fermuarlı Paça",
    pattern: "Regular Jogger",
    materiel: "Pamuk-Polyester-Elastan",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Başarılı Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#DE001B",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
    buyWin: true,
  },
]

export default ContainerList;