const ContainerList = [
  {
    id: 1,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty417/product/media/images/20220506/0/102443165/80327914/1/1_org_zoom.jpg",
    tag: "Hamuen",
    name: "Kadın Siyah Yanı Şeritli Cepli Eşofman Altı 89162",
    star: 4,
    view: 11342,
    price: 110,
    alt: "new",
    video: false,
    coupon: true,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "Nike",
    bodySize: "XXS",
    trotterType: "Dar Paça",
    pattern: "Basic",
    materiel: "Dalgıç Kumaş",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Dört Yıldızlı Ürün",
    color: "#F5E0CC",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
  },
  {
    id: 2,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty572/product/media/images/20221020/9/197769813/160445909/1/1_org_zoom.jpg",
    tag: "CAYA",
    name: "Kadın Siyah Renk Eşofman Altı",
    star: 3,
    view: 4926,
    price: 61,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "Puma",
    bodySize: "XS",
    trotterType: "Fermuarlı Paça",
    pattern: "Wide Leg",
    materiel: "Likra",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Başarılı Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#FFFFFF",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
  },
  {
    id: 3,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty508/product/media/images/20220815/16/160229322/224779670/2/2_org_zoom.jpg",
    tag: "TRENDYOLMİLLA",
    name: "Antrasit Yıkamalı Wide Leg Eşofman Altı",
    star: 4,
    view: 1894,
    price: 275.99,
    alt: "new",
    video: true,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "Mavi",
    bodySize: "M",
    trotterType: "Lastikli Paça",
    pattern: "Jogger",
    materiel: "Polycotton",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Dört Yıldızlı Ürün",
    color: "#A52C36",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
  },
  {
    id: 4,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty565/product/media/images/20221016/2/194629668/80256395/2/2_org_zoom.jpg",
    tag: "Addax",
    name: "Kadın Siyah Paçası Lastikli Eşofman",
    star: 4,
    view: 20697,
    price: 249.50,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "Koton",
    bodySize: "S",
    trotterType: "Normal Paça",
    pattern: "Fitted",
    materiel: "Polyester",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Dört Yıldızlı Ürün",
    color: "#EDE9DE",
    ninePoint: true,
    pictureComment: true,
    freeCargo: true,
  },
  {
    id: 5,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty329/product/media/images/20220209/17/47599109/82766003/3/3_org_zoom.jpg",
    tag: "TRENDYOLMİLLA",
    name: "Gri Selanik Basic Örme Eşofman Altı",
    star: 1,
    view: 13180,
    price: 156.99,
    alt: "new",
    video: false,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "adidas",
    bodySize: "L",
    trotterType: "Jogger",
    pattern: "Comfort",
    materiel: "Polyester",
    waistType: "Normal Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Onaylanmış Satıcı",
    productRating: "1 yıldız ve üzeri",
    starProduct: "Bir Yıldızlı Ürün",
    color: "#DDDDDD",
    ninePoint: false,
    pictureComment: true,
    freeCargo: false,
  },
  {
    id: 6,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty143/product/media/images/20210708/11/108255393/61599742/1/1_org_zoom.jpg",
    tag: "Miorre",
    name: "Unisex Sauna - Zayıflamaya Yardımcı Eşofman",
    star: 2,
    view: 602,
    price: 345.59,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "TrackSuit",
    BrandType: "TRENDYOLMILLA",
    bodySize: "XL",
    trotterType: "Boru Paça",
    pattern: "Straight",
    materiel: "Kadife",
    waistType: "Yüksek Bel",
    usageAreaType: "Fitness / Antrenman",
    sellerType: "Başarılı Satıcı",
    productRating: "2 yıldız ve üzeri",
    starProduct: "İki Yıldızlı Ürün",
    color: "#8B9955",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
  },
  {
    id: 7,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty613/product/media/images/20221129/17/223897525/195866519/1/1_org_zoom.jpg",
    tag: "Tomris",
    name: "Siyah Dar Kalıp Jogger Eşofman Altı",
    star: 3,
    view: 7044,
    price: 59,
    alt: "new",
    video: true,
    coupon: true,
    discount: false,
    fastDelivery: false,
    type: "SweatPants",
    BrandType: "Defacto",
    bodySize: "XXL",
    trotterType: "Lastiksiz Paça",
    pattern: "Standart",
    materiel: "Kadife",
    waistType: "Normal Bel",
    usageAreaType: "Spor",
    sellerType: "Onaylanmış Satıcı",
    productRating: "3 yıldız ve üzeri",
    starProduct: "Üç Yıldızlı Ürün",
    color: "#8B572A",
    ninePoint: true,
    pictureComment: true,
    freeCargo: false,
  },
  {
    id: 8,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty356/product/media/images/20220309/16/66427906/120124808/1/1_org_zoom.jpg",
    tag: "MaesSE",
    name: "Erkek gri günlük eşofman altı jeans fashion",
    star: 5,
    view: 874,
    price: 179.99,
    alt: "new",
    video: false,
    coupon: false,
    discount: true,
    fastDelivery: true,
    type: "SweatPants",
    BrandType: "TRENDYOLMILLA",
    bodySize: "2XL",
    trotterType: "Geniş Paça",
    pattern: "Slim Fit",
    materiel: "Pamuklu",
    waistType: "Yüksek Bel",
    usageAreaType: "Outdoor",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Beş Yıldızlı Ürün",
    color: "#1F3897",
    ninePoint: false,
    pictureComment: true,
    freeCargo: true,
  },
  {
    id: 9,
    category: "Kadın",
    src: "https://cdn.dsmcdn.com/ty581/product/media/images/20221026/9/202614602/75953918/1/1_org_zoom.jpg",
    tag: "Addax",
    name: "Kadın Siyah Paçası Lastikli Eşofman",
    star: 4,
    view: 4417,
    price: 279.50,
    alt: "new",
    video: false,
    coupon: false,
    discount: false,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "Defacto",
    bodySize: "3XL",
    trotterType: "Dar Paça",
    pattern: "Normal",
    materiel: "%100 Organik Pamuk",
    waistType: "Normal Bel",
    usageAreaType: "Günlük",
    sellerType: "Onaylanmış Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Dört Yıldızlı Ürün",
    color: "#71B2FF",
    ninePoint: false,
    pictureComment: true,
    freeCargo: false,
  },
  {
    id: 10,
    category: "Erkek",
    src: "https://cdn.dsmcdn.com/ty201/product/media/images/20211018/15/151687295/59472828/1/1_org_zoom.jpg",
    tag: "Tommy Life",
    name: "Yakalı Kol Garnili Lacivert Erkek Eşofman Takım",
    star: 5,
    view: 772,
    price: 494.92,
    alt: "new",
    video: true,
    coupon: false,
    discount: true,
    fastDelivery: false,
    type: "TrackSuit",
    BrandType: "Nike",
    bodySize: "4XL",
    trotterType: "Fermuarlı Paça",
    pattern: "Büyük Beden",
    materiel: "Kadife",
    waistType: "Yüksek Bel",
    usageAreaType: "Günlük",
    sellerType: "Başarılı Satıcı",
    productRating: "4 yıldız ve üzeri",
    starProduct: "Beş Yıldızlı Ürün",
    color: "#DE001B",
    ninePoint: false,
    pictureComment: true,
    freeCargo: false,
  }
]

export default ContainerList;